name: UHCcore
author: Qzop (Fair) and TheenComputers
version: 1.0
main: core.mainPackage.Main
description: UHCcore - handles all UHC gamemode sided stuff.

commands:
   uhc:
       description: Allows staff to start and stop the uhc.
   config:
       description: Allows players to view config settings and allows staff to change config settings.
   host:
       description: Allows a player to set themselves as host.
   mod:
       description: Allows a player to set themselves as mod.
   team:
       description: Allows players to create teams and add players to their team.
   helpop:
       description: Allows players to send messages privately to staff.
   tp:
       description: Allows staff to teleport to players.
   test:
       description: For developers.
   arena:
       description: Allows Players to join the practice arena.
   border:
       description: Allows staff to shrink the border.
   gm: 
       description: Allows staff to change their GameMode.
   respawn:
       description: Allows staff to respawn a player.
   world:
       description: Deletes a specfic world by name.
   spawn:
      description: Sets the spawn location of a world.
   heal:
      description: Heals a player.
   feed:
      description: Feeds a player.
   alerts:
      description: Allows staff to turn specfic alerts on/off.
   bright:
      description: Allows players to turn full brightness on/off.
   scenarios:
      description: Allows staff to change scenarios and players to view scenarios.